### ISSUE TITLE
Deploy on Galaxy

### ISSUE THREAD

**Issue by mcalamasa** [UHBer/UHBer#5]
Do all work for this in a branch called issue-5

# Description
Deploy the project to galaxy for Milestone 1.

## SubTasks 
- [x] Follow the steps on E59 [http://courses.ics.hawaii.edu/ics314f19/morea/deployment/experience-test-deployment.html](url) to deploy on Galaxy.
- [x] Take two screenshots of dashboard and post them on the #deployment channel on slack.
- [x] Add a link to the uhber.github.io
